language: cpp

install:
- sudo apt-get update
  #- sudo apt-get upgrade --allow-unauthenticated
- sudo apt-get install autotools-dev
- sudo apt-get install automake
#- sudo apt-get install libvcdinfo

script: 
- $CXX --version
- chmod +x bootstrap
- ./bootstrap
- ./configure
- make
